### ISSUE TITLE
Smartphone problem

### ISSUE THREAD

**Issue by violacase** [vue-bulma/vue-bulma#7]
After deploying on a public webserver all works fine on desktop and tablet. On my Samsung GT-I9100 with Android 4.1.2 it unfortunately gives a blank screen. Any idea how to solve this?

**Comment by luventa** [comment]
Hi @violacase , this is not mentioned in Vuejs' doc but Evan said Vuejs only supports Andorid 4.2+
This is the link of a Chinese website https://www.zhihu.com/question/33400353/answer/57831893
